require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MessageThreadsController do

  # This should return the minimal set of attributes required to create a valid
  # MessageThread. As you add validations to MessageThread, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MessageThreadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all message_threads as @message_threads" do
      message_thread = MessageThread.create! valid_attributes
      get :index, {}, valid_session
      assigns(:message_threads).should eq([message_thread])
    end
  end

  describe "GET show" do
    it "assigns the requested message_thread as @message_thread" do
      message_thread = MessageThread.create! valid_attributes
      get :show, {:id => message_thread.to_param}, valid_session
      assigns(:message_thread).should eq(message_thread)
    end
  end

  describe "GET new" do
    it "assigns a new message_thread as @message_thread" do
      get :new, {}, valid_session
      assigns(:message_thread).should be_a_new(MessageThread)
    end
  end

  describe "GET edit" do
    it "assigns the requested message_thread as @message_thread" do
      message_thread = MessageThread.create! valid_attributes
      get :edit, {:id => message_thread.to_param}, valid_session
      assigns(:message_thread).should eq(message_thread)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MessageThread" do
        expect {
          post :create, {:message_thread => valid_attributes}, valid_session
        }.to change(MessageThread, :count).by(1)
      end

      it "assigns a newly created message_thread as @message_thread" do
        post :create, {:message_thread => valid_attributes}, valid_session
        assigns(:message_thread).should be_a(MessageThread)
        assigns(:message_thread).should be_persisted
      end

      it "redirects to the created message_thread" do
        post :create, {:message_thread => valid_attributes}, valid_session
        response.should redirect_to(MessageThread.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved message_thread as @message_thread" do
        # Trigger the behavior that occurs when invalid params are submitted
        MessageThread.any_instance.stub(:save).and_return(false)
        post :create, {:message_thread => {}}, valid_session
        assigns(:message_thread).should be_a_new(MessageThread)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MessageThread.any_instance.stub(:save).and_return(false)
        post :create, {:message_thread => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested message_thread" do
        message_thread = MessageThread.create! valid_attributes
        # Assuming there are no other message_threads in the database, this
        # specifies that the MessageThread created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MessageThread.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => message_thread.to_param, :message_thread => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested message_thread as @message_thread" do
        message_thread = MessageThread.create! valid_attributes
        put :update, {:id => message_thread.to_param, :message_thread => valid_attributes}, valid_session
        assigns(:message_thread).should eq(message_thread)
      end

      it "redirects to the message_thread" do
        message_thread = MessageThread.create! valid_attributes
        put :update, {:id => message_thread.to_param, :message_thread => valid_attributes}, valid_session
        response.should redirect_to(message_thread)
      end
    end

    describe "with invalid params" do
      it "assigns the message_thread as @message_thread" do
        message_thread = MessageThread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MessageThread.any_instance.stub(:save).and_return(false)
        put :update, {:id => message_thread.to_param, :message_thread => {}}, valid_session
        assigns(:message_thread).should eq(message_thread)
      end

      it "re-renders the 'edit' template" do
        message_thread = MessageThread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MessageThread.any_instance.stub(:save).and_return(false)
        put :update, {:id => message_thread.to_param, :message_thread => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested message_thread" do
      message_thread = MessageThread.create! valid_attributes
      expect {
        delete :destroy, {:id => message_thread.to_param}, valid_session
      }.to change(MessageThread, :count).by(-1)
    end

    it "redirects to the message_threads list" do
      message_thread = MessageThread.create! valid_attributes
      delete :destroy, {:id => message_thread.to_param}, valid_session
      response.should redirect_to(message_threads_url)
    end
  end

end
